version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello my world my child.

      - run:
          name: Print the Current Time
          command: date